# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)

## NeoForge
neo_version=21.1.152
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=prospect
mod_name=Prospect
mod_license=MIT License
mod_version=1.0.0-alpha
mod_group_id=alabaster.prospect
mod_authors=AlabasterLeking
mod_description=An exploration and mining mod

## Dependency Info

# JEI
jei_minecraft=1.21
jei_version=19.8.2.99